services:
  coderr_web:
    build: .
    container_name: coderr_web
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      coderr_db:
        condition: service_healthy
    restart: unless-stopped

  coderr_nginx:
    image: nginx:alpine
    container_name: coderr_nginx
    ports:
      - "8002:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      - coderr_web
    restart: unless-stopped

  coderr_db:
    image: postgres:16
    container_name: coderr_db
    environment:
      POSTGRES_DB: coderr
      POSTGRES_USER: coderr
      POSTGRES_PASSWORD: coderr
    volumes:
      - coderr_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coderr"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  coderr_postgres_data:
